### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by Valeriyyy** [PaulDavydov/ProjectManagement#3]
I don't understand the point of this repository. Where is the code?

**Comment by PaulDavydov** [comment]
why do your parents let you exist

**Comment by Valeriyyy** [comment]
I don't understand how this is supposed to end the war in Ukraine

**Comment by PaulDavydov** [comment]
I could have swore you were telling me how much you loved Putin

**Comment by PaulDavydov** [comment]
Master branch should have been updated with the code. It you try to build it, it will not work, due to a few dependencies missing.
